# // Copyright (c) 2i2c-org
# // Distributed under the terms of the Modified BSD License.

name: Build and push container image

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set Environment Variables
        run: |
          echo "DATE_TAG=$(TZ='America/Los_Angeles' date +'%Y.%m.%d')" >> "$GITHUB_ENV"

      - name: Checkout files in repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build and push the image to quay.io
        uses: jupyterhub/repo2docker-action@92fefcbd2b46dd9716f5263a9e740cbc972f6dd9 # master as of 2026-02-23
        with:
          # Make sure username & password/token pair matches your registry credentials
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY: "quay.io"
          ADDITIONAL_TAG: ${{ env.DATE_TAG }}
          IMAGE_NAME: "developmentseed/veda-optimized-data-delivery-image"
